name: Clone and Compress Repo

on:
  workflow_dispatch:

jobs:
  clone-compress-upload:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zstd

      - name: Clone repo
        run: |
          git clone https://github.com/ProjectMatrixx/android_frameworks_base.git source-code

      - name: Compress repo
        run: |
          tar -I 'zstd -19 -T0' -cf source-code.tar.zst source-code

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: android_frameworks_base
          path: source-code.tar.zst
